### ISSUE TITLE
Inegration with IdentityServer 3

### ISSUE THREAD

**Issue by totpero** [PCFDev/Owin.Security.ActiveDirectoryLDAP#4]
Hello, 
Can you create one example how to integrate this provider with IdentityServer 3: https://github.com/IdentityServer/IdentityServer3 ?
I tried but I got stuck...can you help me to integrate this with idsrv3?

**Comment by Aaron-P** [comment]
I'm not sure what that project is, or if this is even relevant, but it in the issue you raised on https://github.com/IdentityServer/IdentityServer3/issues/1775 you set the route to the controller methods to "identity/LDAP/Login", and "identity/LDAP/ExternalLoginCallback" but configured LoginPath to be "/LDAP/Login" and RedirectPath to be "/LDAP/ExternalLoginCallback".  The configured paths are the external routes, they need to be the same.  Other than that I would need a lot more info.

**Comment by totpero** [comment]
I have modify your project and i extend this provider to integrate with identity server 3 and works.
And like your provider i have create lotus notes LDAP provider :+1:  .
